# USB debug logging (only works on central/left side which has USB)
CONFIG_ZMK_USB_LOGGING=y

# BLE split debug logging
CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=100
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_BT_LOG_LEVEL_DBG=y
